<?php

namespace View\Student;

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./public/css/Student.css"/>
    <script async src="./public/script/student.js"></script>
    <title>Main Page</title>
</head>
<body>
    <div id="left-side">
        <img src="./public/img/Logo_Hust.png" alt="HUST" style="width: 60%; padding: 30px 0 0 40px"/><br><br><hr>
        <a class="check-in-js" style="cursor: pointer">Check in</a><hr>
        <a class="check-out-js" style="cursor: pointer">Check out</a><hr> 
        <a href="">Reserve room</a><hr>
        <a href="">Request help</a><hr>
        <a href="./Login.php">Sign out</a>
    </div>
        
    <div id="top-side">
        <a href="">
            <img src="./public/img/notification.png" alt="Notification"
                style="width: 50px; padding: 5px 0 0 10px"/>
        </a>
        <p> Hello,&nbsp;
            <?php
                if(isset($_SESSION['user'])){
                    echo $_SESSION['user'][0][1]." - ". $_SESSION['user'][0][0];
                }
            ?>
        </p>
        <p style="font-size: 30px; margin-top: 10px; padding-right: 250px; color: white; font-weight: 600;">Hệ thống Quản lý Phòng tự học</p>
    </div>
        
    <div id="room-list"> 
        <?php 
            require_once "./bootstrap.php";
            use Controller\RoomController;
                    
            $roomController = new RoomController();
 
            $bdings = $roomController->getAllBuilding();
            foreach($bdings as $bding){ 
                echo "<h1 style='padding-left: 20px;
                                background-color: beige;font-family: sans-serif'>".$bding['name']."</h1>";

                $rooms = $roomController->getRoomByBuilding($bding['buildID']);
                echo "
                <table style=''>
                    <tr>";
                    foreach($rooms as $room){
                        echo "<td style='padding:0px 25px; border-right: 1px solid'>"
                                . "<b>".$room['name']."</b><br><br><i>"
                                .$room['status']."</i></td>";
                    }
                echo "</tr>
                </table>";
            }
    ?>      
    </div>
    
    <div class="modal modal-in-js">
        <form action="" method="post" class="cform cform-js">
            <img src="./public/img/close.jpg" alt="close" class="close close-in-js">
            <header class="form-header">Check in</header>
            <p>Input classroom: <input type="text" name="roomName" style="font-size: 20px" required></p>
            <input type="submit" name="joinRoom" value="Join classroom" class="submit-form">
        </form>
    </div>
    
    <div class="modal modal-out-js">
        <form action="" method="post" class="cform cform-js">
            <img src="./public/img/close.jpg" alt="close" class="close close-out-js">
            <header class="form-header">Check out</header>
            <input type="submit" name="outRoom" value="Out classroom" class="submit-form" style="margin-top: 60px">
        </form>
    </div>
    
    
</body>
</html>
